version: '3'
services:
  postgres-db:
    image: postgres:12.2-alpine
    container_name: postgres-database
    restart: always
    ports:
      - 5432:5432 # external-port:container-port
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=agoodpassword
      - POSTGRES_DB=postgres
    networks:
      - backend-network
    volumes:
      - database_postgres:/var/lib/postgresql/data
  server:
    build: ./server
    container_name: nestjs-backend
    ports:
      - 22802:22802 # external-port:container-port
    volumes:
      - ./config.yml:/usr/src/app/config.yml
      - ./credentials/:/usr/src/app/credentials/
    depends_on:
      - postgres-db
    networks:
      - backend-network
      - middlebridge
volumes:
  database_postgres: {}
networks:
  backend-network: {}
  middlebridge: {}